name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [18]
      fail-fast: false
    name: 'Test on node-${{ matrix.node_version }}, ${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v3
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"

      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
